### PR TITLE
Expand Status Icons

### PR DESCRIPTION
**Pull request by trev-dev**
This pull request adds a whole bunch of new status icons and reminders to help GMs remember what's going on second by second and between sessions, especially if they're in mid combat.

Changes Listed:

1. A whole bunch of new situational statuses/reminders
2. Removal of some icons I thought we'd use, but did not
3. Addition of required icons for some new statuses
4. Re-arrangement of the icon order in an attempt to categorize them and make finding icons easier
5. Rework "pain" states to be more explicit in both the modifiers and the language reference file. I.E. `id: "moderate"` is now `id: "moderate_pain"`.
6. Addition of "counter" icons to help keep track of arbitrary timed things (grenade fuses, seconds to ready, etc).

Ref: https://github.com/crnormand/gurps/issues/242

Screenshot_20210206_114808

### CODE REVIEW

**Comment by crnormand** [comment]
Trev, it is showing conflicts...and it says I need to use the command line to merge.   Did you place icons?

**Comment by trev-dev** [comment]
It just looks like you may have had other future commits that included some icons I deleted since they weren't being used.  This conflict was not here when I submitted the pull request. If it makes it easier, I can resolve it on my end by updating my branch and re-committing the change :)

**Comment by crnormand** [comment]
Yes, please.

**Comment by trev-dev** [comment]
@crnormand Updated and committed!

**Pull request merged**
