### PR TITLE
Quintessence

### PR DESCRIPTION
**Pull request by kbrownridge**
Added Quintessence and Quintessence Points.

### CODE REVIEW

**Comment by crnormand** [comment]
Assuming this round of releases (and bug fixes) will settle down, and I can integrate this this week.

**Comment by kbrownridge** [comment]
Just a note, I've haven't updated my pull request to fix any issues that may have arisen as a result of the recent Foundry updates. One thing of note is that the text in the System Settings option no longer displays correctly, it looks like placeholder text. Also, the way I added it only works per client not as a GM option for everyone.

**Comment by kbrownridge** [comment]
added the following to line 1091 of /lang/en.json to address labelling issue:
"GURPS.settingUseQuintessence": "Use Quintessence",
"GURPS.settingHintUseQuintessence": "If enabled, adds the Quintessence (QN) attribute and allows the use of QP as a resource tracker. Imports these values from GCS if available.",

**Comment by kbrownridge** [comment]
FYI - As of 0.13.13 after I added my changes back, as I have done previously, I'm getting an error.
Looking into it but it's something about an "unregistered setting" but is coming from the actor.js file and a function that's checking the actor move attribute.

**Comment by kbrownridge** [comment]
Well then...I'm just an idiot who accidentally overwrote a setting while using WinMerge. Works fine with 0.13.13.

As you were.

**Comment by crnormand** [comment]
Sorry it took SOOO long... I've merge in the code and preparing a release.

**Comment by kbrownridge** [comment]
No worries, my friend.I understand it’s a low priority item in a very long list.I appreciate that you guys considered adding it at all.Though, I was amused that at least one other person wanted this feature. LOL


Sent from Yahoo Mail for iPhone


On Monday, April 11, 2022, 12:59 PM, Chris Normand ***@***.***> wrote:




Sorry it took SOOO long... I've merge in the code and preparing a release.

**Pull request merged**
